try: print(1223)
except: print('except')

try: print(a)
except: print('except')
